logging:
  level:
    root: ERROR
    org:
      springframework.web: ERROR
      hibernate: ERROR
      apache:
        kafka: ERROR
    com:
      ecsfin: ERROR
spring:
  main.banner-mode: "off"
  output.ansi.enabled: ALWAYS
  sleuth: 
    sampler: 
      probability: 1.0
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    time-zone: UTC
  lifecycle:
    timeout-per-shutdown-phase: 1m
  data:
    mongodb:
      authentication-database: admin
      host: mongo
      password: Ecssupport09
      port: 27017
      username: admin
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
          auto-add-partitions: true
          headers: type
          configuration:
            "linger.ms": 20
            "buffer.memory": 33554432
            "batch.size": 32768
            "compression.type": "snappy"
            "receive.buffer.bytes": 16000000
            "socket.receive.buffer.bytes": 16000000
            "fetch.max.wait.ms": 20
            "fetch.min.bytes": 32768
            auto.offset.reset: earliest
      default:
        producer:
          partitionKeyExpression: headers['traceId']
          partitionCount: 24
          errorChannelEnabled: true
          headerMode: headers
        consumer:
          partitioned: true
          maxAttempts: 1
          defaultRetryable: false
          headerMode: headers
          autoCommitOffset: true
          autoCommitOnError: true
  redis:
    host: redis
    port: 6379
    password:
    lettuce:
      shutdown-timeout: 200ms
      pool:
        max-active: 5
        max-idle: 5
        min-idle: 2
        max-wait: -1ms
eureka:
  instance:
    preferIpAddress: true
    hostname: discovery-service
    metadataMap:
      "prometheus.scrape": "true"
      "prometheus.path": "/actuator/prometheus"
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery-server:8761/eureka}
management:
  endpoints:
    web:
      exposure:
        include: "info,health,prometheus,env"
  endpoint:
    info:
      enabled: true
    shutdown:
      enabled: false      
    health:
      show-details: always
  health:
    probes:
      enabled: true  
    binders:
      enabled: true  
server:
  shutdown:
    GRACEFUL      
company:
  contact:
    name: "ECSFin"
    url: "https://ecsfin.com"
    email: "info@ecsfin.com"
  license: "Copyright © 2020. ECS Fin. All Rights Reserved."
  termsOfService:
    url: "https://ecsfin.com/about-us/our-vision/"
springdoc:
  version: '@springdoc.version@'
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /docs.html
    displayRequestDuration: true
    tagsSorter: alpha
    display-query-params-without-oauth2: true
  cache:
    disabled: true
zeebe:
  client:
    broker:
      contactPoint: "zeebe:26500"
    security:
      plaintext: true
    worker:
      defaultName: worker-name
    cluster:
      replicationFactor: 1
      partitionsCount: 5
    threads:
      cpuThreadCount: 1
      ioThreadCount: 1
---
spring:
  profiles: ofi_qa
  data:
    mongodb:
      host: 172.27.11.139      
      port: 27017
---
spring:
  profiles: rfi_qa
  data:
    mongodb:
      host: 172.27.11.139
      port: 27018
