logging:
  level:
    root: ERROR
    org:
      springframework.web: ERROR
      hibernate: ERROR
      apache:
        kafka: ERROR
spring:
  main.banner-mode: "off"
  output.ansi.enabled: ALWAYS
  sleuth: 
    sampler: 
      probability: 1.0
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    time-zone: UTC
  lifecycle:
    timeout-per-shutdown-phase: 1m
  data:
    mongodb:
      authentication-database: admin
      host: mongo
      password: Ecssupport09
      port: 27017
      username: admin
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
          auto-add-partitions: true
          headers: type
          configuration:
            "linger.ms": 20
            "buffer.memory": 33554432
            "batch.size": 128000
            "compression.type": "snappy"
            "receive.buffer.bytes": 16000000
            "socket.receive.buffer.bytes": 16000000
            "num.replica.fetchers": 3
            "replica.socket.receive.buffer.bytes": 16000000
            "fetch.max.wait.ms": 60
            "fetch.min.bytes": 128000
            auto.offset.reset: earliest
      default:
        producer:
          partitionKeyExpression: headers['traceId']
          partitionCount: 16
          errorChannelEnabled: true
          headerMode: headers
        consumer:
          partitioned: true
          maxAttempts: 1
          defaultRetryable: false
          headerMode: headers
          autoCommitOffset: true
          autoCommitOnError: true
        bindings:
        pacs-cct-in:
          destination: pacs.cct
          consumer.concurrency: 2
          group: ${spring.application.name}
        pacs-cct-out:
          destination: pacs.cct
          group: ${spring.application.name}
          producer:
            partition-count: 16
        pacs-pst-in:
          destination: pacs.pst
          consumer.concurrency: 2
          group: ${spring.application.name}
        pacs-pst-out:
          destination: pacs.pst
          group: ${spring.application.name}
          producer:
            partition-count: 16
        acc-enq-in:
          destination: acc.enq
          consumer.concurrency: 4
          group: ${spring.application.name}
        acc-enq-out:
          destination: acc.enq
          group: ${spring.application.name}
          producer:
            partition-count: 32
        message-out:
          destination: messages
          group: ${spring.application.name}
          producer:
            partition-key-expression: headers['traceId']
            partition-count: 32
        rpp-messages-in:
          destination: rpp.messages
          consumer.concurrency: 4
          group: ${spring.application.name}
        rpp-messages-out:
          destination: rpp.messages
          group: ${spring.application.name}
          producer:
            partition-key-expression: headers['traceId']
            partition-count: 32
        admn-echo-in:
          destination: admn.echo
          consumer.concurrency: 1
          group: ${spring.application.name}
        admn-echo-out:
          destination: admn.echo
          group: ${spring.application.name}
          producer:
            partition-count: 2
        admn-signin-in:
          destination: admn.signin
          consumer.concurrency: 1
          group: ${spring.application.name}
        admn-signin-out:
          destination: admn.signin
          group: ${spring.application.name}
          producer:
            partition-count: 2
        admn-signout-in:
          destination: admn.signout
          consumer.concurrency: 1
          group: ${spring.application.name}
        admn-signout-out:
          destination: admn.signout
          group: ${spring.application.name}
          producer:
            partition-count: 2
        orch-cct-out:
          destination: orch.cct
          group: ${spring.application.name}
          producer:
            partition-count: 16
        orch-cct-in:
          destination: orch.cct
          group: ${spring.application.name}
          consumer.concurrency: 2
        orch-enq-in:
          destination: orch.enq
          group: ${spring.application.name}
          consumer.concurrency: 2
        orch-enq-out:
          destination: orch.enq
          group: ${spring.application.name}
          producer:
            partition-count: 16
        orch-echo-in:
          destination: orch.echo
          consumer.concurrency: 1
          group: ${spring.application.name}
        orch-echo-out:
          destination: orch.echo
          group: ${spring.application.name}
          producer:
            partition-count: 2
        orch-signin-in:
          destination: orch.signin
          consumer.concurrency: 1
          group: ${spring.application.name}
        orch-signin-out:
          destination: orch.signin
          group: ${spring.application.name}
          producer:
            partition-count: 2
        orch-signout-in:
          destination: orch.signout
          consumer.concurrency: 1
          group: ${spring.application.name}
        orch-signout-out:
          destination: orch.signout
          group: ${spring.application.name}
          producer:
            partition-count: 2
        latency-msg-out:
          destination: latency.common
          group: ${spring.application.name}
          producer:
            partition-count: 16
        latency-msg-in:
          destination: latency.common
          group: ${spring.application.name}
          consumer.concurrency: 4
  redis:
    host: redis
    port: 6379
    password:
    lettuce:
      shutdown-timeout: 200ms
      pool:
        max-active: 5
        max-idle: 5
        min-idle: 2
        max-wait: -1ms
eureka:
  instance:
    preferIpAddress: true
    hostname: discovery-service
    metadataMap:
      "prometheus.scrape": "true"
      "prometheus.path": "/actuator/prometheus"
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery-server:8761/eureka}
management:
  endpoints:
    web:
      exposure:
        include: "info,health,prometheus,env"
  endpoint:
    info:
      enabled: true
    shutdown:
      enabled: false      
    health:
      show-details: always
  health:
    probes:
      enabled: true  
    binders:
      enabled: true  
server:
  shutdown:
    GRACEFUL      
company:
  contact:
    name: "ECSFin"
    url: "https://ecsfin.com"
    email: "info@ecsfin.com"
  license: "Copyright © 2020. ECS Fin. All Rights Reserved."
  termsOfService:
    url: "https://ecsfin.com/about-us/our-vision/"
springdoc:
  version: '@springdoc.version@'
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /docs.html
    displayRequestDuration: true
    tagsSorter: alpha
    display-query-params-without-oauth2: true
  cache:
    disabled: true
zeebe:
  client:
    broker:
      contactPoint: "zeebe:26500"
    security:
      plaintext: true
    worker:
      defaultName: worker-name
    cluster:
      replicationFactor: 1
      partitionsCount: 5
    threads:
      cpuThreadCount: 1
      ioThreadCount: 1
---
spring:
  profiles: ofi_qa
  data:
    mongodb:
      host: 40.76.236.117
      port: 60000
---
spring:
  profiles: rfi_qa
  data:
    mongodb:
      host: 40.76.184.149
      port: 60000
