server:
  port: 8850
spring:
  application:
    name: accnt-enq-query
  data:
    mongodb:
      authentication-database: admin
      database: account-enquiry-query
      host: mongo
      password: Ecssupport09
      port: 27017
      username: admin
spring.cloud.stream:
  bindings:
    acc-enq-out:
      destination: acc.enq
      group: ${spring.application.name}
    acc-enq-in:
      destination: acc.enq
      consumer.concurrency: 3
      group: ${spring.application.name}
      
message:
  service:
    ip: message-query
    port: 8849  
    
---
spring:
  profiles: local
  data:
    mongodb:
      host: localhost
message:
  service:
    ip: localhost
    port: 8849
