server:
  port: 8850
logging:
  level:
     com:
      ecsfin:
         service:
          accnt_enq:
             query: INFO
spring:
  application:
    name: accnt-enq-query
  data:
    mongodb:
      authentication-database: admin
      database: account-enquiry-query
      host: mongo
      password: Ecssupport09
      port: 27017
      username: admin
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: false

spring.cloud.stream:
  bindings:
    acc-enq-out:
      destination: acc.enq
      group: ${spring.application.name}
    acc-enq-in:
      destination: acc.enq
      consumer.concurrency: 8
      group: ${spring.application.name}
      
message:
  service:
    ip: message-query
    port: 8849 

    
---
spring:
  profiles: local
  data:
    mongodb:
      host: localhost
message:
  service:
    ip: localhost
    port: 8849
    
---
spring:
  profiles: ofi_qa
message:
  service:
    ip: 172.27.11.131
    port: 30849
    
---
spring:
  profiles: rfi_qa
message:
  service:
    ip: 172.27.11.135
    port: 30849
