server:
  port: 8847
logging:
  level:
    com:
      ecsfin:
        acc_enq: ERROR
spring:
  application:
    name: account-enquiry-service
  data:
    mongodb:
      database: account-enquiry
  cloud.stream:
    bindings:
      acc-enq-out:
        destination: acc.enq
        group: ${spring.application.name}
      acc-enq-in:
        destination: acc.enq
        consumer.concurrency: 8
        group: ${spring.application.name}
      orch-enq-out:
        destination: orch.enq
        group: ${spring.application.name}
zeebe:
  bpmnFiles:
    - outbound-AccEnq.bpmn
    - Inbound-AccEnq.bpmn
  bpmnProcessId: InitiateCustEnq
