server:
  port: 8847
spring:
  application:
    name: account-enquiry-service
  data:
    mongodb:
      authentication-database: admin
      database: account-enquiry
      host: mongo
      password: Ecssupport09
      port: 27017
      username: admin
spring.cloud.stream:
  bindings:
    acc-enq-out:
      destination: acc.enq
      group: ${spring.application.name}
    acc-enq-in:
      destination: acc.enq
      consumer.concurrency: 4
      group: ${spring.application.name}
zeebe:
  bpmnFile: outbound-AccEnq.bpmn
  bpmnProcessId: InitiateCustEnq
  
---
spring:
  profiles: local
  data:
    mongodb:
      host: localhost
      port: 27017
      