server:
  port: 8060
logging:
  level:
    com:
      ecsfin:
        service:
          enterprise:
            integrator: ERROR
spring:
  application:
    name: enterprise-integrator
  data:
    mongodb:
      authentication-database: admin
      host: mongo      
      database: integrator-messages
    jpa:
      repositories:
        enabled: false      
  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Ecssupport09
  #autoconfigure:
  #  exclude: "org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration"
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
      #hibernate.default_schema: intgdb
  cloud:
    stream:
     bindings:
       pacs-cct-in:
        destination: pacs.cct
        consumer.concurrency: 8
        group: ${spring.application.name}
       pacs-cct-out:
        destination: pacs.cct
        group: ${spring.application.name}
       acc-enq-in:
        destination: acc.enq
        consumer.concurrency: 8
        group: ${spring.application.name}
       acc-enq-out:
        destination: acc.enq
        group: ${spring.application.name}
       message-out:
        destination: messages
        producer:
          partition-key-expression: headers['traceId']
        group: ${spring.application.name}
       message-in:
        destination: messages
        group: ${spring.application.name}
        
timeOutSec: 20
slpTimeinMS: 1000

eai:
  urls:
    urlDetails:
      - id: 1
        creditorAccountType: CCRD
        url: http://192.168.65.91:7010/mockRACE_SOA_ACCTINFO_getDepAcctBalance_webservices_getDepAcctBalance_Binder?wsdl
        soapAction: RACE_SOA_ACCTINFO_getDepAcctBalance_webservices_getDepAcctBalance_Binder_getAcctBalanceCA
      - id: 2
        creditorAccountType: SVGS
        url: http://192.168.65.91:7010/mockRACE_SOA_ACCTINFO_getDepAcctBalance_webservices_getDepAcctBalance_Binder?wsdl
        soapAction: RACE_SOA_ACCTINFO_getDepAcctBalance_webservices_getDepAcctBalance_Binder_getAcctBalanceCA
      - id: 3
        creditorAccountType: LOAN
        url: http://192.168.65.91:7011/mockRACE_SOA_ACCTINFO_enquireLoanBalance_webservices_provider_wsEnquireLoanBalanceSvc_Binder?wsdl
        soapAction: RACE_SOA_ACCTINFO_enquireLoanBalance_webservices_provider_wsEnquireLoanBalanceSvc_Binder_enquireLoanBalance
      - id: 4
        creditorAccountType: CACC
        url: http://192.168.65.91:7010/mockRACE_SOA_ACCTINFO_getDepAcctBalance_webservices_getDepAcctBalance_Binder?wsdl
        soapAction: RACE_SOA_ACCTINFO_getDepAcctBalance_webservices_getDepAcctBalance_Binder_getAcctBalanceCA
      - id: 5
        creditorAccountType: FUND
        url: http://192.168.65.91:7018/mockRACE_SOA_PAYMENT_fundsTransfer_webservices_wsFundsTransferSvc_Binder?wsdl
        soapAction: RACE_SOA_PAYMENT_fundsTransfer_webservices_wsFundsTransferSvc_Binder_fundsTransfer
      - id: 6
        creditorAccountType: FCRD
        url: http://192.168.65.91:7019/mockRACE_SOA_PAYMENT_fpxLcaRefund_webservices_provider_wsFpxLcaRefundSvc_Binder?wsdl
        soapAction: RACE_SOA_PAYMENT_fpxLcaRefund_webservices_provider_wsFpxLcaRefundSvc_Binder_fpxLcaRefund
---
spring:
  profiles: jpa
  data:
    mongodb:
      host: localhost
      repositories:
        type: none
  autoconfigure:
    exclude: "org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration,org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration"
---
spring:
  profiles: local
mongo:
  sharding: false  
---
spring:
  profiles: rfi_qa
mongo:
  sharding: false
---
spring:
  profiles: ofi_qa
mongo:
  sharding: false
---
spring:
  profiles: platform
mongo:
  sharding: false
---
spring:
  profiles: ofi_demo
mongo:
  sharding: false
---
spring:
  profiles: rfi_demo
mongo:
  sharding: false
---
spring:
  profiles: rfi_demo,ofi_demo,ofi_qa,rfi_qa
eai:
  urls:
    urlDetails:
      - id: 1
        creditorAccountType: CCRD
        url: http://172.27.11.150:3032/mockRACE_SOA_ACCTINFO_getDepAcctBalance_webservices_getDepAcctBalance_Binder?wsdl
        soapAction: RACE_SOA_ACCTINFO_getDepAcctBalance_webservices_getDepAcctBalance_Binder_getAcctBalanceCA
      - id: 2
        creditorAccountType: SVGS
        url: http://172.27.11.150:3032/mockRACE_SOA_ACCTINFO_getDepAcctBalance_webservices_getDepAcctBalance_Binder?wsdl
        soapAction: RACE_SOA_ACCTINFO_getDepAcctBalance_webservices_getDepAcctBalance_Binder_getAcctBalanceCA
      - id: 3
        creditorAccountType: LOAN
        url: http://172.27.11.150:3032/mockRACE_SOA_ACCTINFO_enquireLoanBalance_webservices_provider_wsEnquireLoanBalanceSvc_Binder?wsdl
        soapAction: RACE_SOA_ACCTINFO_enquireLoanBalance_webservices_provider_wsEnquireLoanBalanceSvc_Binder_enquireLoanBalance
      - id: 4
        creditorAccountType: CACC
        url: http://172.27.11.150:3032/mockRACE_SOA_ACCTINFO_getDepAcctBalance_webservices_getDepAcctBalance_Binder?wsdl
        soapAction: RACE_SOA_ACCTINFO_getDepAcctBalance_webservices_getDepAcctBalance_Binder_getAcctBalanceCA
      - id: 5
        creditorAccountType: FUND
        url: http://172.27.11.150:3032/mockRACE_SOA_PAYMENT_fundsTransfer_webservices_wsFundsTransferSvc_Binder?wsdl
        soapAction: RACE_SOA_PAYMENT_fundsTransfer_webservices_wsFundsTransferSvc_Binder_fundsTransfer
      - id: 6
        creditorAccountType: FCRD
        url: http://172.27.11.150:3032/mockRACE_SOA_PAYMENT_fpxLcaRefund_webservices_provider_wsFpxLcaRefundSvc_Binder?wsdl
        soapAction: RACE_SOA_PAYMENT_fpxLcaRefund_webservices_provider_wsFpxLcaRefundSvc_Binder_fpxLcaRefund
