server:
  port: 8849
# logging:
#   level:
#     com:
#       ecsfin:
#         service:
#           message:
#             query: INFO
spring:
  application:
    name: message-query
  data:
    mongodb:
      database: message-query
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: false
spring.cloud.stream.bindings:
  message-in:
    destination: messages
    consumer.concurrency: 8
    group: ${spring.application.name}
  rpp-messages-in:
    destination: rpp.messages
    consumer.concurrency: 8
    group: ${spring.application.name}

management:
  metrics:
    export:
      elastic:
        step: 30s
        host: http://elasticsearch-master.workflow.svc.cluster.local:9200

elasticsearch:
  connection.url: elasticsearch-master.workflow.svc.cluster.local:9200
  
notify.threshold: 1000

eureka:
 instance:
   metadataMap:
     "prometheus.scrape": "true"
     "prometheus.path": "/actuator/prometheus"
---
spring:
  profiles: local
  data:
    mongodb:
      host: localhost
elasticsearch:
  connection.url: localhost:9200

notify.threshold: 4

---
spring:
  profiles: platform
  data:
    mongodb:
      #host: 192.168.65.137
      #port: 60000
      
---
notification:
  email: siddharthajay189@gmail.com, abhilash.as@m.ecsfin.com, midhunnair.sk@m.ecsfin.com
  noReplyAddress: eventnotify.ecsfin@gmail.com
