server:
  port: 9595
logging:
  level:
    com:
      ecsfin:
        workflow:
          cct.inbound: WARN
workflow:
  cct:
    outbound:
      timeout: 5000
    inbound:
      timeout: 5000
  actenq:
    outbound:
      timeout: 5000
    inbound:
      timeout: 5000
  echo:
    outbound:
      timeout: 20000
    max:
      attempts: 3
spring:
  application:
    name: orchestration-service
  main:
    allow-bean-definition-overriding: true
  cloud:
    stream:
      bindings:
        pacs-cct-out:
          destination: pacs.cct
          group: ${spring.application.name}
        pacs-cct-in:
          destination: pacs.cct
          group: ${spring.application.name}
          consumer.concurrency: 8
        acc-enq-out:
          destination: acc.enq
          group: ${spring.application.name}
        acc-enq-in:
          destination: acc.enq
          group: ${spring.application.name}
          consumer.concurrency: 8
        admn-echo-out:
          destination: admn.echo
          group: ${spring.application.name}
        admn-echo-in:
          destination: admn.echo
          consumer.concurrency: 8
          group: ${spring.application.name}
        admn-signin-in:
          destination: admn.signin
          consumer.concurrency: 8
          group: ${spring.application.name}
        admn-signin-out:
          destination: admn.signin
          group: ${spring.application.name}
        admn-signout-in:
          destination: admn.signout
          consumer.concurrency: 8
          group: ${spring.application.name}
        admn-signout-out:
          destination: admn.signout
          group: ${spring.application.name}
        orch-cct-in:
          destination: orch.cct
          group: ${spring.application.name}
          consumer.concurrency: 8
        orch-cct-out:
          destination: orch.cct
          group: ${spring.application.name}
        orch-enq-in:
          destination: orch.enq
          group: ${spring.application.name}
          consumer.concurrency: 8
        orch-enq-out:
          destination: orch.enq
          group: ${spring.application.name}
        orch-echo-in:
          destination: orch.echo
          consumer.concurrency: 8
          group: ${spring.application.name}
        orch-signin-in:
          destination: orch.signin
          consumer.concurrency: 8
          group: ${spring.application.name}
        orch-signout-in:
          destination: orch.signout
          consumer.concurrency: 8
          group: ${spring.application.name}
