server:
  port: 9595
logging:
  level:
    com:
      ecsfin:
        workflow:
          cct.inbound: INFO
workflow:
  cct:
    outbound:
      timeout: 5000
    inbound:
      timeout: 5000
  actenq:
    outbound:
      timeout: 5000
    inbound:
      timeout: 5000
  echo:
    outbound:
      timeout: 20000
    max:
      attempts: 3
spring:
  application:
    name: orchestration-service
  main:
    allow-bean-definition-overriding: true
