server:
  port: 8899
logging:
  level:
    com:
      ecsfin:
        pacs: ERROR
spring:
  application:
    name: pacs-service
  data:
    mongodb:
      database: pacs-cct
  redis:
    host: pacs-redis
    port: 6379
zeebe:
  bpmn:
    cct:
      files: 
        - Outbound-CCT.bpmn
        - Inbound-CCT.bpmn
      incoming:
        processId: InboundCCTFlow
      outgoing:
        processId: InitiateCCT
---
spring:
  profiles: local
  redis:
    host: ${REDIS_HOST:192.168.45.23}
    port: 6379
    password:
# ---
# spring:
#   profiles: rfi_qa,ofi_qa
#   data:
#     mongodb:
#       host: mongo
#       port: 27017
