server:
  port: 8898
spring:
  application:
    name: pacs-query
  data:
    mongodb:
      authentication-database: admin
      database: pacs-query
      host: mongo
      password: Ecssupport09
      port: 27017
      username: admin
spring.cloud.stream.bindings:
  pacs-cct-in:
    destination: pacs.cct
    consumer.concurrency: 8
    group: ${spring.application.name}

message:
  service:
    ip: message-query
    port: 8849  
    
---
spring:
  profiles: local
  data:
    mongodb:
      host: localhost
message:
  service:
    ip: localhost
    port: 8849
    
---
spring:
  profiles: platform
message:
  service:
    ip: 192.168.45.11
    port: 30849
    
---
spring:
  profiles: ofi_dev
message:
  service:
    ip: 192.168.45.15
    port: 30849
    
---
spring:
  profiles: rfi_dev
message:
  service:
    ip: 192.168.45.19
    port: 30849
    
---
spring:
  profiles: ofi_qa
message:
  service:
    ip: 172.27.11.131
    port: 30849
    
---
spring:
  profiles: rfi_qa
message:
  service:
    ip: 172.27.11.135
    port: 30849
    
---
spring:
  profiles: ofi_demo
message:
  service:
    ip: 172.27.11.81
    port: 30849
      
---
spring:
  profiles: rfi_demo
message:
  service:
    ip: 172.27.11.121
    port: 30849
