server:
  port: 8899
logging:
  level:
    com:
      ecsfin:
        pacs: WARN
spring:
  application:
    name: pacs-service
  data:
    mongodb:
      database: pacs-cct
  cloud.stream.bindings:
    pacs-cct-in:
      destination: pacs.cct
      consumer.concurrency: 8
      group: ${spring.application.name}
    pacs-cct-out:
      destination: pacs.cct
      group: ${spring.application.name}
    orch-cct-out:
      destination: orch.cct
      group: ${spring.application.name}
    orch-enq-out:
      destination: orch.enq
      group: ${spring.application.name}
zeebe:
  bpmn:
    cct:
      files: 
        - Outbound-CCT.bpmn
        - Inbound-CCT.bpmn
      incoming:
        processId: InboundCCTFlow
      outgoing:
        processId: InitiateCCT
---
spring:
  profiles: local
  redis:
    host: ${REDIS_HOST:192.168.45.23}
    port: 6379
    password:
---
spring:
  profiles: rfi_qa,ofi_qa
  data:
    mongodb:
      host: mongo
      port: 27017
